### ISSUE TITLE
How to add multiple filter queries

### ISSUE THREAD

**Issue by leiting6** [freedev/solr-import-export-json#103]
Can this parameter --filterQuery only be added once? How to add multiple conditional filter queries?

**Comment by freedev** [comment]
Hi @leiting6 sorry for the late response. Have you figured out? I'll try to add some example with multiple conditional filters

**Comment by leiting6** [comment]
No, Please add multiple conditional filters.

**Comment by freedev** [comment]
@leiting6 I have created a new branch [filter_queries](https://github.com/freedev/solr-import-export-json/tree/filter_queries) with this new feature. Can you test it?

**Comment by freedev** [comment]
@leiting6  another solution is making leverage on the [solr standard query parser and the AND operator](https://solr.apache.org/guide/solr/latest/query-guide/standard-query-parser.html#the-boolean-operator-and). 

    ./run.sh -s http://localhost:8983/solr/collection -a export -o /tmp/collection.json \
          -f "field1:A AND field2:B AND field3:C"

**Comment by freedev** [comment]
closing the issue for inactivity

**Comment by leiting6** [comment]
Hi @freedev 

> @leiting6 another solution is making leverage on the [solr standard query parser and the AND operator](https://solr.apache.org/guide/solr/latest/query-guide/standard-query-parser.html#the-boolean-operator-and).
> 
> ```
> ./run.sh -s http://localhost:8983/solr/collection -a export -o /tmp/collection.json \
>       -f "field1:A AND field2:B AND field3:C"
> ```

The ways is very fantastic! 
Thanks.
