### ISSUE TITLE
after import  the data has difference between with the export json file

### ISSUE THREAD

**Issue by AceAttorney** [freedev/solr-import-export-json#25]
hi i used the tools as the tutorial said 

but found something  out of my expect 

in export json file ,the data is key:value format ,but when i import to another solr server , they looks like key:list['value'] fomart

can anyone help me ? thanks

**Comment by AceAttorney** [comment]
this one is the old server data , the data format is key:value

![企业微信截图_5df5785c-acf2-4d99-a7c1-8598d83eeed9(1)](https://user-images.githubusercontent.com/13723456/66912392-122f2500-f045-11e9-9249-7000f1113e81.png)

and this is the new one ,the data just like  key:list['value'] format 

![企业微信截图_a38086dd-46de-4c54-b667-5c817e29a8cc(1)](https://user-images.githubusercontent.com/13723456/66912372-0c394400-f045-11e9-90da-4320c7bcb9d6.png)

**Comment by damionjunk** [comment]
I ran into this issue when I forgot to create the schema in the new core as it was in the core I exported data from. When I defined all my fields and types, the values matched and everything was good.

**Comment by AceAttorney** [comment]
@damionjunk  thanks!  i will give a try!
