### ISSUE TITLE
How do we pass the credentials IF solr has authentication enabled.

### ISSUE THREAD

**Issue by srikanthanthagiri123** [freedev/solr-import-export-json#28]

**Comment by roygeorgeP** [comment]
I have created a fork off - https://github.com/roygeorgeP/solr-import-export-json-1.git - you can see how its done for read.

**Comment by freedev** [comment]
Hi @roygeorgeP thanks for pointing out, could you write a PR?

**Comment by freedev** [comment]
Hi @srikanthanthagiri123, @roygeorgeP 
I've added the basic authentication looking at @roygeorgeP implementation was pretty easy.
