### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by alankwyu** [freedev/solr-import-export-json#3]
In App.java line 256, should it be the following instead?
DateFormat df = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");

**Comment by freedev** [comment]
I've just created a branch json_datetime_format

**Comment by alankwyu** [comment]
ConfigFactory.java line 106 missing this call
c.setDateTimeFormat(dateTimeFormat);

After adding that, calling the app with -F "yyyy-MM-dd'T'HH:mm:ss'Z'"

**Comment by freedev** [comment]
Thanks I've fixed the code.
