### ISSUE TITLE
When you enabled Solr auth it could be export but not import

### ISSUE THREAD

**Issue by LiuEnqi260570** [freedev/solr-import-export-json#43]
Thanks  for your  project! It helps me to solved my job very usefully.But when I import data for solrcloud, 401 was happened.
Perform the following:
`./run.sh -s http://localhost:8983/solr/hdqs_solr_collection1 -a import -o /home/leq/solr.json -u solr -p password`
problem occured
![image](https://user-images.githubusercontent.com/42128322/78543639-8647ca00-782b-11ea-89b9-1f7824ff6f60.png)
may you give some advices?

**Comment by freedev** [comment]
Hi, looking at error code it seems you have a problem with the authentication. Are you sure of your credentials?  
You could double check your credentials trying to call directly http://localhost:8983/ with some simple tool like curl or wget. For example 

    wget --http-user=USERNAME --http-password=PASSWORD http://localhost:8983/solr/hdqs_solr_collection1/select?q=*:*&rows=1

**Comment by freedev** [comment]
And *usually* localhost does not have any kind of authentication enabled, you don't need to use username and password.

**Comment by LiuEnqi260570** [comment]
This is my host
`./run.sh -s http://d-bdap-dn-101.bigdata.com:8983/solr/collection1 -a import -o /home/hdqs/leq/data/collection1.json -u solr -p password`
Using an export is feasible,however it's couldn't be imported.

**Comment by freedev** [comment]
Hi, not sure I got your reply. 
Had you tried to execute the wget command I suggested? And, if yes, with what results?

**Comment by LiuEnqi260570** [comment]
Hi, I executed the wget command and was able to download it.However, I still can't carry out import operation. I have read the source code of your project and found no basic authentication of import

**Comment by freedev** [comment]
Hi, thanks for the debug. I've created a branch "basic_auth with the fix, had you time to try this version?

**Comment by LiuEnqi260570** [comment]
Hello, thank you very much for your help. I downloaded and used this branch, but my solrcloud does not seem to support this authentication method, and the following error occurred. I used the CDH version of solr4.10.3
![image](https://user-images.githubusercontent.com/42128322/80300480-c9181480-87cf-11ea-94d4-7d706e5641d8.png)
IDEA:
![image](https://user-images.githubusercontent.com/42128322/80300490-de8d3e80-87cf-11ea-8afb-153df39b3b96.png)

**Comment by freedev** [comment]
Do you know which auth method supports your SolrCloud?

**Comment by LiuEnqi260570** [comment]
Hi, This is my method of authentication:
![image](https://user-images.githubusercontent.com/42128322/80326084-3d9f9180-886a-11ea-86a0-d2050b7251f3.png)

**Comment by LiuEnqi260570** [comment]
Hi,I was successded,thank you again! With your help, I modified the authentication method.
![image](https://user-images.githubusercontent.com/42128322/80578945-cc173d00-8a3b-11ea-909f-07627e96f6b1.png)
![image](https://user-images.githubusercontent.com/42128322/80578967-d802ff00-8a3b-11ea-9ebf-a7897daf97e8.png)

**Comment by freedev** [comment]
This code is not from my app. Have you tested the branch?

**Comment by LiuEnqi260570** [comment]
Yes,just add this line 
![image](https://user-images.githubusercontent.com/42128322/81073513-55d27900-8f1a-11ea-8cec-9e4562c7f7b0.png)

**Comment by freedev** [comment]
could you open a pull request?

**Comment by freedev** [comment]
Hi @IvanBaricic, the PR works fine, I've merged pull request. I did some import/export test too adding a simple config [server/solr/security.json](https://lucene.apache.org/solr/guide/8_6/authentication-and-authorization-plugins.html#in-standalone-mode) in standalone mode: user solr password SolrRocks. 

```
{
"authentication":{
   "blockUnknown": true,
   "class":"solr.BasicAuthPlugin",
   "credentials":{"solr":"IV0EHq1OnNrj6gvRCwvFwTrZ1+z1oBbnQdiVC3otuq0= Ndd7LKvVBAaZIF0QAVi1ekCfAJXr1GGfLtRUXhgrF8c="}
},
"authorization":{
   "class":"solr.RuleBasedAuthorizationPlugin",
   "permissions":[{"name":"security-edit",
      "role":"admin"}],
   "user-role":{"solr":"admin"}
}}
```

Thanks to everyone for your contribution, I think we can close the issue now.
