### ISSUE TITLE
--skipCount on exporting

### ISSUE THREAD

**Issue by chamish** [freedev/solr-import-export-json#44]
It is a great practical tool, it work great bu I have a record of 1.5 billion. I suppose it will take 5-6 days just import to json file. The problem is I want to skip some number of line . Because there can be errors and this will make me start all over. So how can I skip recorded Items. or lines.

**Comment by freedev** [comment]
The skip parameter comes from a contribution and actually works only during the import step.
Just to understand, do you have all the documents just in one shard or the documents are divided in more shards?

**Comment by freedev** [comment]
The import file must have just one line for each document (one json), the --skupCount parameter just skips the lines while reading the file.

**Comment by freedev** [comment]
I think it isn't a good idea create only one file of 1.5 billion of documents, would be much simple import you create many smaller files. And if each document has its own unique key, you could even import more files concurrently without incurring in collisions problems. With the unique key the import step is idempotent so, in case of problems, during the import you can retry as many times as you want.

**Comment by chamish** [comment]
Thanks for answer , I definetly agreee it is a risk to have a single file. So your proposal is use --filterQuery option right ? . But how I will use this sample "uniqueKey":"e2e34db06a562250b4477233e1ffeabc", using timestamp ?

**Comment by chamish** [comment]
It will be great that if you can explain the usage of -k uniquekey function .

**Comment by freedev** [comment]
Unique key is a basic concept of Solr. Usually all the documents have a field named “id” (string). The -k parameter is usefu when you are exporting (a great number of) documents because Solr needs to have them in a deterministic order. When you have to import the -k parameter is useless, just be sure you have defined a schema, or at least you’re aware of the schema you’re using

**Comment by chamish** [comment]
Thanks for information, our database not included any id, meanwhile is it possible to devide data week or day by day. while exporting ?

**Comment by chamish** [comment]
Could you tell me in what format we should use to select date time range .I am using the command below but having several errors.I also tried all versions of " and ' . But it is unsuccessful. I also change date format too but errors are same . -F 

./run.sh -s http://localhost:8983/solr/test -a export -o /tmp/test.json -F "yyyy-MM-dd'T'HH:mm:ss'Z'" -f "update_date:[2020-03-05T00:00:00Z TO 2020-03-06T00:00:00Z]"

solr.search.SyntaxError: Cannot parse 'update_date:[2020-03-05T00:00:00Z': Encountered "<EOF>" at line 1, column 33.
Was expecting:
    "TO" ...

**Comment by chamish** [comment]
Ok there is a problem on run.sh it is solved.
