### ISSUE TITLE
Issue building on Centos

### ISSUE THREAD

**Issue by vinnytroia** [freedev/solr-import-export-json#86]
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /opt/solr-import-export-json/src/main/java/it/damore/solr/importexport/App.java:[32,36] cannot access org.apache.solr.client.solrj.SolrQuery
  bad class file: /root/.m2/repository/org/apache/solr/solr-solrj/9.0.0/solr-solrj-9.0.0.jar(org/apache/solr/client/solrj/SolrQuery.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.216 s
[INFO] Finished at: 2022-06-20T01:47:02Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project import-export: Compilation failure
[ERROR] /opt/solr-import-export-json/src/main/java/it/damore/solr/importexport/App.java:[32,36] cannot access org.apache.solr.client.solrj.SolrQuery
[ERROR]   bad class file: /root/.m2/repository/org/apache/solr/solr-solrj/9.0.0/solr-solrj-9.0.0.jar(org/apache/solr/client/solrj/SolrQuery.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR]
[ERROR] -> [Help 1]

not even sure where to start. 

i agree, a pre-built version would be awesome.

**Comment by freedev** [comment]
Hi @vinnytroia 
What version of Java are you using?

**Comment by freedev** [comment]
Hi @vinnytroia, this kind of error raises with Java 8 and Solr 9.0.0
With the new version of solr 9.0.0 you have to use at least Java 11, although with Solr 8.x you can use Java 1.8 or higher.
I have just modified the pom.xml file and README.md to make the things clear.

**Comment by freedev** [comment]
Closing inactive issue.
