### ISSUE TITLE
Clarify Licensing on GitHub

### ISSUE THREAD

**Issue by williamdean** [freedev/solr-import-export-json#87]
The project in GitHub is listed as having an Apache 2.0 license, but I see GPLv3 in code and in a gpl.txt file. If it is still GPLv3 licensed and contains other Apache 2.0 licensed code then I would suggest then renaming the gpl.txt file to "gpl-3.0-license.txt" so that GitHub detects it as having multiple licenses.

An example screenshot of what that looks like.

<img width="313" alt="Screen Shot 2022-07-26 at 5 15 43 PM" src="https://user-images.githubusercontent.com/1407609/181114416-00c93ae2-7a44-4b9e-99de-e63b453295e0.png">

**Comment by freedev** [comment]
Hi @williamdean thanks for pointing this out. Let me double check.

**Comment by freedev** [comment]
Hi @williamdean, the situation should be clear now.
