### ISSUE TITLE
import json file

### ISSUE THREAD

**Issue by rajanim** [freedev/solr-import-export-json#98]
Could you please provide a sample json file that has multiple json objects as input with each object having multi-valued field. For example

`[{"id": "1", "keywords_dict.en": ["losing money", "businessman and wins", "stock exchange trading", "stock traders", "new york stock exchange", "global financial crisis", "financial traders", "stock market"]}, {"id": "2", "keywords_dict.en": ["woman", "gift"]}]`

**Comment by freedev** [comment]
hi @rajanim in the output there is just one line each json. 

Could you please provide a sample json file that has multiple json objects as input with each object having multi-valued field. For example

```
{"id": "1", "keywords_dict.en": ["losing money", "businessman and wins", "stock exchange trading", "stock traders", "new york stock exchange", "global financial crisis", "financial traders", "stock market"]}
{"id": "2", "keywords_dict.en": ["woman", "gift"]}
```
